// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {bridge} from '../models';

export function LAssetPreviewStop():Promise<string>;

export function LDirectoryOutputOpen(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function LDirectorySourceOpen(arg1:string):Promise<void>;

export function LInspectionStart(arg1:backend.LPreference):Promise<backend.LReport>;

export function LMergerRun(arg1:backend.LPreference):Promise<backend.LReport>;

export function LPickerFFmpegOpen():Promise<string>;

export function LPickerFileOpen():Promise<Array<string>>;

export function LPickerFolderOpen():Promise<string>;

export function LPreferenceLoad():Promise<backend.LPreference>;

export function LPreferenceSave(arg1:backend.LPreference):Promise<void>;

export function LProgramProfileRead():Promise<bridge.LProgramProfile>;

export function LReportOutputSet(arg1:backend.LReport,arg2:backend.LPreference):Promise<backend.LReport>;

export function LTaskStop():Promise<string>;

export function LTemporaryClean(arg1:backend.LPreference):Promise<backend.LTemporaryResult>;
