// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LAssetPreviewStop() {
  return window['go']['bridge']['LProgram']['LAssetPreviewStop']();
}

export function LDirectoryOutputOpen(arg1, arg2, arg3) {
  return window['go']['bridge']['LProgram']['LDirectoryOutputOpen'](arg1, arg2, arg3);
}

export function LDirectorySourceOpen(arg1) {
  return window['go']['bridge']['LProgram']['LDirectorySourceOpen'](arg1);
}

export function LInspectionStart(arg1) {
  return window['go']['bridge']['LProgram']['LInspectionStart'](arg1);
}

export function LMergerRun(arg1) {
  return window['go']['bridge']['LProgram']['LMergerRun'](arg1);
}

export function LPickerFFmpegOpen() {
  return window['go']['bridge']['LProgram']['LPickerFFmpegOpen']();
}

export function LPickerFileOpen() {
  return window['go']['bridge']['LProgram']['LPickerFileOpen']();
}

export function LPickerFolderOpen() {
  return window['go']['bridge']['LProgram']['LPickerFolderOpen']();
}

export function LPreferenceLoad() {
  return window['go']['bridge']['LProgram']['LPreferenceLoad']();
}

export function LPreferenceSave(arg1) {
  return window['go']['bridge']['LProgram']['LPreferenceSave'](arg1);
}

export function LProgramProfileRead() {
  return window['go']['bridge']['LProgram']['LProgramProfileRead']();
}

export function LReportOutputSet(arg1, arg2) {
  return window['go']['bridge']['LProgram']['LReportOutputSet'](arg1, arg2);
}

export function LTaskStop() {
  return window['go']['bridge']['LProgram']['LTaskStop']();
}

export function LTemporaryClean(arg1) {
  return window['go']['bridge']['LProgram']['LTemporaryClean'](arg1);
}
